CREATE SCHEMA IF NOT EXISTS app;
SET search_path TO app;

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('admin', 'volunteer')),
      created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    );

    CREATE TABLE IF NOT EXISTS participants (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      registration_id TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      email TEXT,
      year TEXT,
      program TEXT,
      department TEXT,
      payment_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (payment_status IN ('pending', 'verified', 'rejected')),
      payment_proof_url TEXT,
      qr_token TEXT UNIQUE,
      whatsapp_sent INTEGER NOT NULL DEFAULT 0,
      whatsapp_sent_at TEXT,
      email_sent INTEGER NOT NULL DEFAULT 0,
      email_sent_at TEXT,
      food_claimed INTEGER NOT NULL DEFAULT 0,
      claimed_at TEXT,
      claimed_by_user_id INTEGER,
      created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
      updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    );

    CREATE TABLE IF NOT EXISTS invitation_settings (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      message_template TEXT NOT NULL,
      poster_path TEXT,
      poster_enabled INTEGER NOT NULL DEFAULT 1,
      updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    );

    CREATE INDEX IF NOT EXISTS idx_participants_phone ON participants(phone);
    CREATE INDEX IF NOT EXISTS idx_participants_qr_token ON participants(qr_token);
    CREATE INDEX IF NOT EXISTS idx_participants_payment_status ON participants(payment_status);
  
ALTER TABLE participants ADD COLUMN IF NOT EXISTS whatsapp_status TEXT NOT NULL DEFAULT 'not_sent';
ALTER TABLE participants ADD COLUMN IF NOT EXISTS whatsapp_error TEXT;
CREATE TABLE IF NOT EXISTS poster_files (
  path TEXT PRIMARY KEY,
  content BYTEA NOT NULL,
  content_type TEXT NOT NULL
);
REVOKE ALL ON SCHEMA app FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA app FROM PUBLIC;
